name: helm-lint
on: [ push, workflow_dispatch ]
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3        

      - name: Configure Git
        run: |        
          git config user.name "nataliabelogolovaya"
          git config user.email "belogolovayanv@gmail.com"
     
      - name: Install Helm
        uses: azure/setup-helm@v3     
      
      - name: helm-check
        uses: igabaydulin/helm-check-action@0.1.4
        env:
          CHART_LOCATION: ./jenkins/jenkins/
          CHART_VALUES: ./jenkins/jenkins/values.yaml   
